### ISSUE TITLE
pyepics run in windows 10, the pv is not connected

### ISSUE THREAD

**Issue by gilbertguoze** [pyepics/pyepics#223] opened 2021-09-16 14:12 UTC
when i use `pyepics` to connect pv in windows10 , the pv shows non connect, bus when i use the dmc elipse, i can get the pv information, why? how can i deal with this situation, 3x
additionally, the `carepeater` is not in the path environment, are there some standard steps to use pyepics in windows10?

**Comment by newville** [comment] 2021-09-16 14:59
`carepeater` should not be necessary.  I guess the problem is with setting the environmental variable EPICS_CA_ADDR_LIST and whether the PVs are on the same subnet.  

When you run 'dmc eclipse', is that on same Windows machine?

**Comment by gilbertguoze** [comment] 2021-09-18 01:50
first, thank u for replying so quickly
the `EPICS_CA_ADDR_LIST` how to set it?, please tell me.
the pvs are on the same subnet, and 'dmc eclipse' is on the same machine, the figure below is the proof.
![批注 2021-09-17 112752](https://user-images.githubusercontent.com/40510280/133868040-f788d724-b8bc-437c-bd6c-a0d792cf8ae9.png)
and there is another interesting thing, that is:
i wrote the code in a .py file, named `test.py`, when i use `python test.py` to call , it shows the pv `SCZGK0002` not connected, but when i use command terminal, input `python` to start python env, and input `import epics, epics.PV('SCZGK0002).info` the pv is connected, as the figure below shows. maybe is the PORT problem? how i deal with this situation
![批注 2021-09-17 124205](https://user-images.githubusercontent.com/40510280/133868043-17c0d64a-58d2-49b1-9c8d-b7e61f513239.png)
![批注 2021-09-17 114810](https://user-images.githubusercontent.com/40510280/133868048-5ef0d620-cf2f-41c9-8f57-fa255c532016.png)

**Comment by newville** [comment] 2021-09-19 23:56
@gilbertguoze  You should be able to set `EPICS_CA_ADDR_LIST` to an IP address or series of IP address that either host the PVs you want to connect to, or will broadcast to those IP addresses. A simple, common approach would be to set it to the broadcast address of your network, which will typically be "xxx.yyy.zzz.255", allowing you to reach PVs at "xxxx.yyy.zzz.1" through "xxx.yyy.zzz.254" (where "xxx.yyy.zzz" is really your IP subnet range).

You can do that as a system-wide environmental variable so that all applications can connect to epics PVs. In Python, you can also do 
```
import os
import epics
os.environ['EPICS_CA_ADDR_LIST'] = 'xxx.yyy.zzz.255'
...
```

From within python, you just need to do that before doing any real Channel Access work, but it can be after import `epics`.

But also:  from your screenshots, it looks to be like it is working and you are connecting to PVs, just maybe slower than you might expect.  Note that connecting is not instaneous, might take 5 to 500 ms, depending on your workload and network (it could sometimes be longer for "far away" PVs, say outside of your subnet). 

So, it may be that you just need to wait a bit between creating a PV and starting that network connection and being sure that the PV is really readable.  You could do something like

```
import epics
pv1 = epics.PV('SCGZK002')
pv1.connect()
print(pv1.value())
```

or 
```
pv1 = epics.PV('SCGZK002')
print(pv1.get())
```

both of which wil wait for the connection to be established.

**Comment by gilbertguoze** [comment] 2021-09-28 12:51
finally, i got it done, thank u

**Comment by newville** [comment] 2021-09-28 15:09
@gilbertguoze OK, I'll close this issue.  Seems resolved.

**Closed by newville** 2021-09-28 15:09 UTC
