### ISSUE TITLE
Dealing with 'nan' values

### ISSUE THREAD

**Issue by fonty422** [pyepics/pyepics#185] opened 2019-11-20 12:29 UTC
I have a setup where a callback fires and returns:
pvname, char_value, timestamp, status, severity, upper_alarm_limit_, lower_alarm_limit, upper_warning_limit, lower_alarm_limit, and host.
However, I get nans for the lower values. I understand that this has something to do with how epics deals with lower alarm and warning levels that are effectively meaningless (in this case they are both equal to zero, and zero is set to NO_ALARM), but is there any way to return the zero anyway?
At the moment I end up with a separate callback on those to grab them if they change (a rare event, sure, but possible still).
Also, other than a unique callback, any way to also include the PV description so I only need a single callback for all data?

**Comment by newville** [comment] 2019-11-20 13:02
@fonty422   FWIW, I believe that   `upper_alarm_limit`, `upper_warning_limit`, `lower_alarm_limit`, and `lower_warning_limit` are often `nan` -- probably "unless explicitly configured", and probably because it doesn't always make sense to have a lower_warning_limit.

By default (and from the list of attributes you report for your callback), pyepics casts PV as using the "TIME" form (in pyepics that is `PV(pvname, form='time', ...)` which corresponds to DBR_TIME_* records.
These don't include all the limits, so some may get set to `None` (not `nan`) in the callback.

You can also subscribe to the "CTRL" form with `PV(pvname, form='ctrl', ...)`, which will replace the accurate timestamps (from the server side) with a more complete set of limit values.  Again, some of the less-than-universally-used limits might be `nan`.  I think that comes from the record.

Since they don't change very often, a common approach would be to grab the CTRL vars once and then monitor the TIME form:

     mypv = epics.PV(pvname)
     mypv.get_ctrlvars()
     mypv.add_callback(MyMonitorMethod)


>  Also, other than a unique callback, any way to also include the PV description so I only need a single callback for all data?

Which description do you mean?   PVs don't have a description field.

**Comment by fonty422** [comment] 2019-11-20 13:24
Thanks for the speedy reply.
I'm using the `form="ctrl"` currently, but will consider switching to the `time` format instead. But I see the point, and will probably continue to go with the method of a unique callback for the upper and lower warning/alarm limits, along with the description one, to ensure I get the recorded values for these. Just wondered if there was a way to do it all in one rather than many callbacks.

We have PVs that have a `.DESC` suffix (i.e. `PV_NAME:SOME_MONITOR.DESC`) which is a string description of the PV - quite useful when the PV name isn't all that descriptive in its self. You can call it directly with a standard `get()` request, much like you can call the value of the PV with `PV("PV_NAME:SOME_MONITOR.VAL").get()`. I understand that the .VAL isn't required, but its more like a `caget()`. But I assume I've been mistaken that this is a field of the PV and rather a PV in its own right?

**Comment by newville** [comment] 2019-11-20 21:30
@fonty422 

> I'm using the form="ctrl" currently, but will consider switching to the time format instead. But I see the point, and will probably continue to go with the method of a unique callback for the upper and lower warning/alarm limits, along with the description one, to ensure I get the recorded values for these. Just wondered if there was a way to do it all in one rather than many callbacks.

You should be able to just do `mypv.get_ctrlvars()` to read the current CTRL variables for any PV.   You should not have to monitor or read limits separately unless you expect them to change.

> We have PVs that have a .DESC suffix (i.e. PV_NAME:SOME_MONITOR.DESC) which is a string description of the PV - quite useful when the PV name isn't all that descriptive in its self.  You can call it directly with a standard get() request, much like you can call the value of the PV with PV("PV_NAME:SOME_MONITOR.VAL").get(). I understand that the .VAL isn't required, but its more like a caget(). But I assume I've been mistaken that this is a field of the PV and rather a PV in its own right?

Sure, many epics **records** will have a DESC field.  That is a separate PV from a VAL or other fields in the record. 

There is not a universal way to get the description for a PV.  It often works to that if

    PVThing:property.VAL

has some records value, that PVThing:property.DESC will hold a string describing that instance of a record.   Sure, that's a common pattern and very useful.   But the PV itself `PVThing:property.VAL` or `PVThing:propery.RBV` does not have a description attribute and you have to infer the existence of a description PV and somehow know its name.  It very often works to test a record's RTYP and DTYP fields to better guess what other record fields will be available as PVs.

But it still all means that the description goes with the Record (motor, ai, etc) and not with a PV.

You might find pyepics `Device` as a simple way to map a set of related PVs to a single Python object.

**Comment by fonty422** [comment] 2019-11-27 22:25
Thanks again.
I'm happy with the requirements for callback function for limits and descriptions to meet my application needs.
But the callback does something strange with the limits and units where the first time it fires it returns the limits perfectly fine in scientific notation, but the second time it returns it as 0.0.
A similar thing occurs for the units where the first time it returns the units as, say, mBar and every subsequent trigger returns an empty string. Not `None`, but an empty string.
Are these epics things, or pyepics things? And any way around it?

**Comment by newville** [comment] 2019-11-27 22:51
@fonty422  please include an example code with output.

**Comment by fonty422** [comment] 2019-11-27 22:57
`
def callback(
    pvname=None,
    value=None,
    char_value=None,
    timestamp=None,
    status=None,
    severity=None,
    upper_alarm_limit=None,
    lower_alarm_limit=None,
    upper_warning_limit=None,
    lower_warning_limit=None,
    host=None,
    units=None,
    **kw):
    
    print(type(units), len(units), type(upper_alarm_limit), str(upper_alarm_limit))
    print(
        "\npvname=",pvname,
        "\nvalue=",value,
        "\nchar_value=",char_value,
        "\ntimestamp=",timestamp,
        "\nstatus=",status,
        "\nseverity=",severity,
        "\nupper_alarm_limit=",upper_alarm_limit,
        "\nlower_alarm_limit=",lower_alarm_limit,
        "\nupper_warning_limit=",upper_warning_limit,
        "\nlower_warning_limit=",lower_warning_limit,
        "\nhost=",host,
        "\nunits=",units,
        "\n****************\n"
    )

PV("XXX:YYY", form="ctrl", callback=callback)
`
Output:
`
<PV 'XXX:YYY', count=1, type=ctrl_double, access=read-only>
<class 'str'> 4 <class 'float'> 1e-06

pvname= XXX:YYY
value= 5.5e-11 
char_value= 5e-11 
timestamp= 1574895335.099462 
status= 0 
severity= 0 
upper_alarm_limit= 1e-06 
lower_alarm_limit= 1.4e-11 
upper_warning_limit= 1e-07 
lower_warning_limit= 1.4e-11 
host= 10.6.19.91:5064 
units= mbar 
****************

<class 'str'> 0 <class 'float'> 0.0

pvname= XXX:YYY 
value= 1.3e-11 
char_value= 1e-11 
timestamp= 1574895337.9731014 
status= 5 
severity= 2 
upper_alarm_limit= 0.0 
lower_alarm_limit= 0.0 
upper_warning_limit= 0.0 
lower_warning_limit= 0.0 
host= 10.6.19.91:5064 
units=  
****************
`

**Comment by fonty422** [comment] 2019-11-27 23:13
Or would using the pyepics `device` option help to clear this up?

**Comment by newville** [comment] 2019-11-27 23:46
@fonty422 Hm, that does seem very weird that value, status, and severity are all different and that all the CTRL fields are unset in the second callback. I'm not sure why that would happen...

Do you see that with the command-line `caget` using the appropriate switches to get the CTRL values.

**Comment by fonty422** [comment] 2019-11-27 23:56
`caget XXX:YYY.EGU`, `caget XXX:YYY.HIHI`,` caget XXX:YYY.HIGH`, `caget XXX:YYY.LOLO`, and `caget XXX:YYY.LOW` all return the respective and expected result for `units`,` upper_alarm_limit`, `upper_alarm_warning`, `lower_alarm_warning`, and `lower_alarm_limit`

**Comment by newville** [comment] 2019-11-28 00:06
@fonty422 OK, I can reproduce your observations:  Creating a PV with `form='ctrl`' and adding using a callback, the *first* callback (like on creation) does get all the control values, but subsequent callbacks do not.    Not sure what's wrong, but I will investigate.

**Comment by fonty422** [comment] 2019-11-28 00:07
Great, thanks. At least it's able to be replicated...

**Comment by fonty422** [comment] 2019-11-28 00:12
also note that the results are the same if you have a standard callback (i.e. don't set the form) but first call the PV with `get_ctrlvars()`

**Comment by newville** [comment] 2019-11-28 00:37
@fonty422 OK -- I'll try to figure that out.

**Comment by newville** [comment] 2019-11-29 18:29
@fonty422 after a little more investigation, here's what I am seeing.  Perhaps you or someone else could confirm/deny that the behavior I see is consistent with what you see:

I can create and monitor an epics PV of `ctrl` type, the users callback function gets valid control values (say, `units`, `precision`, `upper_alarm_limit`) when the value changes, at least for most of the PVs I deal with.   That is something like this:

    import epics
    def onchange(pvname, value, units='_nounits_', precision=-1, **kws):
          print(' -> ', pvname, value, units, precision)
    
    pv = epics.PV(pvname, form='ctrl', callback=onchange)
    while True:
        epics.poll()

usually works to correctly print the name, value, units, and precision in each call.

For PVs on a different subnet (for me, that is "other PVs from the APS storage ring"), I get valid values of value for all callbacks, but only get correct values for `units` and `precision` the first time the callback is run.  For subsequent calls, the values for these control fields are 0 or ''.

I've traced this back all the way to the `_unpack_metadata()` function in `ca.py`.  It looks to me like the calls to `ca._onMonitorEvent` really are getting empty / zero values for these PVs.  I suspect that this is in libCA.

Since I only see this for PVs outside of our subnet, I wonder if this may be because those PVs have to be transmitted through a gateway, or perhaps because they are served using an older version of libca.   But I'm not sure whether either of those is correct.

**Comment by ralphlange** [comment] 2019-11-29 18:36
See https://github.com/epics-extensions/ca-gateway/issues/11

**Comment by newville** [comment] 2019-11-29 20:47
@ralphlange  Thanks - I guess I should have remembered that from just 4 years ago, but I didn't.  
OK, we'll file this as a known behavior when using a gateway.  

@fonty422  Does that match your observations too: are the PVs you are trying to monitor coming through a gateway?

**Comment by ralphlange** [comment] 2019-11-29 21:39
I did release a contributed fix for the Gateway a few weeks ago - maybe you can talk someone into running a test using 2.1.2 to verify it?!

**Comment by newville** [comment] 2019-11-29 22:58
@ralphlange Oh, OK, great.  That should probably find its way into production soon...

**Comment by fonty422** [comment] 2019-12-04 08:35
Yep, I can confirm that it's a gateway issue. One of our controls people wrote a little test script in C and showed it's purely a gateway thing. 
Hopefully the work by @ralphlange will fit nicely.
For now I will work on a simple get-first-time-save-to-database-hope-it-doesn't-change thing. We do sometimes temporarily drop low limits if we have a fleeting alarm on night shift, but out application is intended to have a soft limit change to account for this, so perhaps it's not that important.

**Comment by fonty422** [comment] 2019-12-04 08:38
But in addition, if there's a new version including the gateway fix i'm interested in trying it out as we're still very much in development so don't need anything super stable.

**Comment by ralphlange** [comment] 2019-12-04 08:47
For the Gateway fix to be activated, the CA Gateways in your facility's production systems need to be updated and redeployed.
The people in charge of such services are usually (and rightfully) very conservative with respect to updates. It may help to contact them and tell them you are affected by a bug in the Gateway code that has been fixed by a newer release. A user request might be required to start an update cycle.

**Comment by fonty422** [comment] 2019-12-04 09:01
👍

**Comment by newville** [comment] 2019-12-04 12:49
@fonty422  I expect that pyepics callbacks on CTRL-type PVs will work correctly once the fix for the CA Gateway is installed.  They do work within a subnet, so I think the receiving end is OK.  Famous last words?  I do admit that I don't know for sure, as the gateway I use also shows the problem, and is out of my control.

**Closed** 2023-07-27 12:31 UTC
